### ISSUE TITLE
Error: typesense version 28.0 is not supported

### ISSUE THREAD

**Issue by SlimDeluxe** [typesense/typesense-lando-plugin#1]
Hello,
thank you for implementing the plugin.
Adding the following:
```
  typesense:
    type: typesense:27.1
    portforward: 8108
    apiKey: abc
```
... to the lando config works, but I wonder why doesn't it allow to use the latest version of Typesense?

If I change the above to:
```
  typesense:
    type: typesense:28
    portforward: 8108
    apiKey: abc
```

... I get this while doing a lando rebuild:

```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: typesense version 28.0 is not supported
    at new LandoLando (/snapshot/core/builders/_lando.js)
    at new LandoService (/snapshot/core/builders/_service.js)
    at new LandoTypesense (/home/omer/.lando/plugins/typesense/services/typesense/builder.js:45:7)
    at /snapshot/core/hooks/app-add-v3-services.js
    at arrayEach (/snapshot/core/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/snapshot/core/node_modules/lodash/lodash.js:9410:14)
    at /snapshot/core/hooks/app-add-v3-services.js
    at AsyncEvents.<anonymous> (/snapshot/core/app.js)
From previous event:
    at AsyncEvents.handle (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/events.js
    at process.processImmediate (node:internal/timers:483:21)
From previous event:
    at AsyncEvents.emit (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/app.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

**Comment by jasonbosco** [comment]
Resolved in 353a4f94a9b324c7969d23e96883ad9ccfff611f. Could you try now?

**Comment by SlimDeluxe** [comment]
Yes, that works. Thanks 🙂 
However I also needed to specify the minor version, so:
```
  typesense:
    type: typesense:28.0
    portforward: 8108
    apiKey: abc
```
